### ISSUE TITLE
Error using chckxywp (line 76) There should be at least 2 data sites

### ISSUE THREAD

**Issue by ultrai** [pangyuteng/caserel#2]
Hi,
Thanks for the tool box and great tutorial on DP. I haverun the framework on Duke AMD dataset and it has run smooth but on extending it to DME data se it runs into "Error using chckxywp (line 76)
There should be at least 2 data sites" error.

dataset: http://people.duke.edu/~sf59/Chiu_BOE_2014_dataset.htm

TIA,
SPK Karri

**Comment by pangyuteng** [comment]
Can you paste the stack trace?  Based on the information you gave me, I can only say that the code is breaking due to segmenting diseased dataset, and that proper error handling was not implemented.  When I developed this, I segmented only cases with no disease and with drusen.

**Comment by ultrai** [comment]
> In getHyperReflectiveLayers at 112
  In getRetinalLayersCore at 39
  In getRetinalLayers at 129
  In bench_mark at 27

**Comment by pangyuteng** [comment]
Try updating the second argument in the method for getHyperReflectiveLayers and see if you get the hyper reflective layers.

**Comment by ultrai** [comment]
Last few columns in some images are  below mean value. so include indexes in rough isos dosn't include last columns leading a 'inf' distance.  A temporary way around Iam removing 'include indexes' (yep computationally expensive).
