### ISSUE TITLE
bugs in compiling getRetinalLayersExample.m

### ISSUE THREAD

**Issue by KAMH** [pangyuteng/caserel#3]
Hello Pangyu Teng,
I tried to compile your Matlab script: '[getRetinalLayersExample.m](https://github.com/pangyuteng/caserel/blob/master/getRetinalLayersExample.m)'. 
But I got this error message. Can you help me to fix it?

```
segmenting image 1 of 3
segmenting image 2 of 3
segmenting image 3 of 3
segmentation saved to /Users/kaspar/Downloads/caserel-master/exampleOCTimage0001.tif_octSegmentation.mat
Warning: The input to STR2FUNC
"/Users/kaspar/Downloads/caserel-master/exampleOCTimage0001.tif_octSegmentation.mat" is not
a valid function name. This will generate an error in a future release. 
> In octSegmentationGUI (line 61)
  In getRetinalLayersExample (line 135) 
Subscript indices must either be real positive integers or logicals.
```

Thanks,
Kaspar

**Comment by pangyuteng** [comment]
Hi Kaspar. Thank you for your interest in trying this code out. I don't have Matlab installed anymore, but my guess is the version of Matlab is probably newer than the one used during development.

**Comment by pangyuteng** [comment]
Feel free to update the code and fix it and I can merge your fix. That would be awesome.

**Comment by pangyuteng** [comment]
Looks like it is just a warning, so ignore the warning for now.  If the GUI is not working, try overlaying the results on the images yourself. The segmentation should been saved in to disk already, which happend few lines above the launching of the GUI.
